---
# - name: Ensure CNI directory exists
#   file:
#     path: /etc/cni/net.d
#     state: directory
#     mode: '0755'
#   tags: cni

- name: Install Flannel CNI
  command: kubectl apply -f https://github.com/flannel-io/flannel/releases/latest/download/kube-flannel.yml
  register: flannel_result
  changed_when: "'created' in flannel_result.stdout"
  when:
    - cni_plugin == "flannel"
    - inventory_hostname in groups['control_plane']
  tags: cni

- name: Install Calico CNI
  command: kubectl apply -f https://docs.projectcalico.org/manifests/calico.yaml
  register: calico_result
  changed_when: "'created' in calico_result.stdout"
  when:
    - cni_plugin == "calico"
    - inventory_hostname in groups['control_plane']
  tags: cni
