---
- name: Install Flannel CNI
  command: kubectl apply -f https://github.com/flannel-io/flannel/releases/latest/download/kube-flannel.yml
  register: flannel_result
  changed_when: "'created' in flannel_result.stdout"
  when:
    - cni_plugin == "flannel"
    - inventory_hostname in groups['control_plane']
  tags: cni

- name: Install Calico CNI
  command: kubectl create -f https://raw.githubusercontent.com/projectcalico/calico/v3.29.3/manifests/tigera-operator.yaml -f https://raw.githubusercontent.com/projectcalico/calico/v3.29.3/manifests/custom-resources.yaml
  register: calico_result
  changed_when: "'created' in calico_result.stdout"
  when:
    - cni_plugin == "calico"
    - inventory_hostname in groups['control_plane']
  tags: cni
