---
- name: Create CNI directories
  file:
    path: "{{ item }}"
    state: directory
    mode: '0755'
  with_items:
    - /opt/cni/bin
    - /etc/cni/net.d
  tags: containerd, cni

- name: Check for existing CNI plugins
  stat:
    path: /opt/cni/bin/bridge
  register: cni_plugins_stat
  tags: containerd, cni

- name: Download CNI plugins
  get_url:
    url: "https://github.com/containernetworking/plugins/releases/download/v1.4.0/cni-plugins-linux-amd64-v1.4.0.tgz"
    dest: /tmp/cni-plugins.tgz
    mode: '0644'
  when: not cni_plugins_stat.stat.exists
  tags: containerd, cni

- name: Install CNI plugins
  unarchive:
    src: /tmp/cni-plugins.tgz
    dest: /opt/cni/bin
    remote_src: yes
  tags: containerd, cni

- name: Create basic CNI configuration
  copy:
    content: |
      {
        "cniVersion": "0.4.0",
        "name": "cni-bridge",
        "plugins": [
          {
            "type": "bridge",
            "bridge": "cni0",
            "isGateway": true,
            "ipMasq": true,
            "hairpinMode": true,
            "ipam": {
              "type": "host-local",
              "ranges": [
                [{"subnet": "10.244.0.0/24"}]
              ]
            }
          },
          {
            "type": "portmap",
            "capabilities": {"portMappings": true}
          }
        ]
      }
    dest: /etc/cni/net.d/10-bridge.conf
    mode: '0644'
  when: cni_plugin == "none"
  tags: containerd, cni
