---
- name: Install containerd
  apt:
    name: containerd
    state: present
  when: ansible_os_family == "Debian"
  tags: containerd

- name: Create containerd config directory
  file:
    path: /etc/containerd
    state: directory
    mode: '0755'
  tags: containerd

- name: Generate default containerd config
  shell: containerd config default > /etc/containerd/config.toml
  args:
    creates: /etc/containerd/config.toml
  tags: containerd

- name: Configure containerd to use systemd cgroup driver
  replace:
    path: /etc/containerd/config.toml
    regexp: 'SystemdCgroup = false'
    replace: 'SystemdCgroup = true'
  notify: Restart containerd
  tags: containerd

- name: Ensure containerd is started and enabled
  systemd:
    name: containerd
    state: started
    enabled: yes
  tags: containerd
