---
- name: Install containerd
  apt:
    name: containerd
    state: present
  when: ansible_os_family == "Debian"
  tags: containerd

- name: Create containerd config directory
  file:
    path: /etc/containerd
    state: directory
    mode: '0755'
  tags: containerd

- name: Create containerd config from template
  template:
    src: containerd-config.toml.j2
    dest: /etc/containerd/config.toml
    mode: '0644'
  notify: Restart containerd
  tags: containerd

- name: Ensure containerd is started and enabled
  systemd:
    name: containerd
    state: started
    enabled: yes
  tags: containerd
