---
- name: Check if cluster is already initialized
  stat:
    path: /etc/kubernetes/admin.conf
  register: kubeadm_init_stat
  tags: kubernetes

- name: Initialize Kubernetes cluster
  command: kubeadm init --config=/etc/kubernetes/kubeadm-config.yaml --v=5
  register: kubeadm_init
  when: not kubeadm_init_stat.stat.exists
  tags: kubernetes

- name: Create .kube directory for current user
  file:
    path: "{{ ansible_env.HOME }}/.kube"
    state: directory
    mode: '0755'
  tags: kubernetes

- name: Copy admin.conf to user's kube config
  copy:
    src: /etc/kubernetes/admin.conf
    dest: "{{ ansible_env.HOME }}/.kube/config"
    remote_src: yes
    owner: "{{ ansible_user }}"
    group: "{{ ansible_user }}"
    mode: '0600'
  when: not kubeadm_init_stat.stat.exists or kubeadm_init.changed
  tags: kubernetes

- name: Generate join command for workers
  command: kubeadm token create --print-join-command
  register: join_command
  when: not kubeadm_init_stat.stat.exists or kubeadm_init.changed
  tags: kubernetes

- name: Copy join command to local file
  local_action: copy content="{{ join_command.stdout_lines[0] }}" dest="./join-command"
  when: join_command.changed
  become: no
  tags: kubernetes

- name: Remove control-plane taint from master (single node cluster)
  command: kubectl taint nodes --all node-role.kubernetes.io/control-plane-
  ignore_errors: yes
  when: not kubeadm_init_stat.stat.exists or kubeadm_init.changed
  tags: kubernetes
