---
- name: Initialize Kubernetes cluster
  command:
    argv:
      - kubeadm
      - init
      - --config=/etc/kubernetes/kubeadm-config.yaml
  register: kubeadm_init

- name: Set up kubeconfig for current user
  block:
    - name: Create .kube directory
      file:
        path: "{{ ansible_env.HOME }}/.kube"
        state: directory
        mode: '0755'

    - name: Copy admin.conf to user's kubeconfig
      copy:
        src: /etc/kubernetes/admin.conf
        dest: "{{ ansible_env.HOME }}/.kube/config"
        remote_src: yes
        owner: "{{ ansible_user_id }}"
        group: "{{ ansible_user_id }}"
        mode: '0600'
  when: kubeadm_init.changed
  become: yes

# - name: Remove control-plane taint (for single node cluster)
#   command: kubectl taint nodes --all node-role.kubernetes.io/control-plane-
#   ignore_errors: yes
#   when: kubeadm_init.changed
#   tags: kubernetes
