---
- name: Check if node is already joined
  stat:
    path: /etc/kubernetes/kubelet.conf
  register: kubelet_conf_stat
  tags: kubernetes

- name: Join the cluster
  command: "{{ hostvars['k8s-master']['join_command'].stdout }}"
  when: not kubelet_conf_stat.stat.exists
  tags: kubernetes
