---
# - name: Prepare nodes for Kubernetes
#   import_playbook: prepare-nodes.yaml

- name: Kubernetes master deployment
  hosts: control_plane
  become: yes
  tasks:
    - name: Deploy master node
      include_role:
        name: kubernetes
        tasks_from: deploy-master.yaml

    - name: Install CNI plugin
      include_role:
        name: cni
