- name: Retrieve and append Kubernetes kubeconfig
  hosts: control_plane
  become: true  # Elevate privileges to root on the remote machine
  tasks:
    - name: Fetch admin.conf from control plane node
      ansible.builtin.fetch:
        src: /etc/kubernetes/admin.conf
        dest: ./admin.conf
        flat: yes
      register: fetched_kubeconfig

    - name: Append kubeconfig to local config
      ansible.builtin.blockinfile:
        path: "{{ lookup('env', 'HOME') }}/.kube/config"
        block: "{{ lookup('file', './admin.conf') }}"
        create: yes
        mode: '0600'
      delegate_to: localhost
      run_once: true
      become: false
      when: fetched_kubeconfig.changed
