- name: Retrieve and upsert Kubernetes kubeconfig
  hosts: control_plane
  become: true
  tasks:
    - name: Fetch admin.conf from control plane node
      ansible.builtin.fetch:
        src: /etc/kubernetes/admin.conf
        dest: ./admin.conf
        flat: yes
      register: fetched_kubeconfig

    - name: Merge kubeconfig into local config
      ansible.builtin.command:
        cmd: >
          KUBECONFIG={{ lookup('env', 'HOME') }}/.kube/config:./admin.conf
          kubectl config view --merge --flatten > ~/.kube/config
      delegate_to: localhost
      run_once: true
      become: false
      when: fetched_kubeconfig.changed
